# .goreleaser.yml
version: 2
project_name: stargate

before:
  hooks:
    - go mod tidy

builds:
  - id: stargate
    main: .
    binary: stargate
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
     - CGO_ENABLED=0 

archives:
  - # This single archive definition handles all OSes.
    # The default format is 'tar.gz', which is used for linux and darwin.
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip'] # Override the format to 'zip' for Windows builds.

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'